Feat/todo list
majishanred/webbee-todo pull request #1
Opened 2024-06-18 12:32 UTC by majishanred

Тудушка готова

2024-06-19 09:00 UTC, myaak requested changes

2024-06-19 09:00 UTC, myaak commented on package.json
> +    "@types/uuid": "^9.0.8",
Почему типы вообще в этих депсах

2024-06-19 09:00 UTC, myaak commented on src/App.tsx
> +const StyledList = styled.ul`
Такие вещи можно выносить в отдельные файлы для чистоты. Или писать их в самом низу под компонентом Сверху они засоряют много места. Обычно делаем файлик `Component.styled`

2024-06-19 09:00 UTC, myaak commented on src/App.tsx
> +  const filteredTasks = filterInput
По хорошему такие вещи в useMemo закидывать.

2024-06-19 09:00 UTC, myaak commented on src/App.tsx
> +  function onAdd(todo_item: TodoListElemBody) {
Т.к ты передаешь это вниз у тебя реденрятся деточки. Нужно исправить. Ну и по хорошему все-таки стрелками привыкать пользоваться. Чтобы хоистинга не было лишнего

2024-06-19 09:00 UTC, myaak commented on src/components/TodoInputForm.tsx
> +  & > button {
А если потом я захочу другую кнопку импортанты писать?

2024-06-19 09:00 UTC, myaak commented on src/components/TodoInputForm.tsx
> +      <button onClick={() => handleOnCreate()} type="button">
Тут можно и без `() =>` обойтись.
`onClick={handleCreate}`

2024-06-19 09:00 UTC, myaak commented on src/components/TodoListElem.tsx
> +  todo_item: TodoElemBody;
Такие вещи лучше в отдельные типы выносить. Существуют компоненты с десятками пропов

2024-06-19 09:00 UTC, myaak commented on src/components/TodoListElem.tsx
> +  const handleOnSaveClick: FormEventHandler = (e) => {
Тут стрелку используешь. А почему в других местах fun declaration. Определись ( везде стрелка )

2024-06-19 09:00 UTC, myaak commented on src/components/TodoListElem.tsx
> +  const handleOnDeleteClick = () => onDelete(todo_item);
Какой смысл в этих функциях?

2024-06-19 09:00 UTC, myaak commented on src/components/TodoListElem.tsx
> +        <input name="taskInput" defaultValue={todo_item.task}></input>
Зачем делать тег двойным? `<input />`

2024-06-19 09:00 UTC, myaak commented on src/components/TodoListElem.tsx
> +    onUpdate(updatedTodo);
А теперь представим что у тебя на апдейт асинхронное действие ( на бек отправляешь ). Получается я уже не в эдите и не знаю че там с моей тудухой?

2024-06-19 09:00 UTC, myaak commented on src/App.tsx
> +  function onUpdate(todo_item: TodoListElem) {
Определись со стилем переменных.
Все пишем в camelCase. У тебя где-то camel, где-то snake_case.

2024-06-19 09:00 UTC, myaak commented on src/App.tsx
> +    setTasks(() => [...tasks, newTodo]);
Очень плохо, а если нужно две тудушки добавить последовательно?

2024-06-19 09:00 UTC, myaak commented on src/App.tsx
> +    setTasks(() => [...newArr]);
Какой смысл от колбека и спреда тут?

2024-06-19 09:00 UTC, myaak commented on src/components/TodoInputForm.tsx
> +    onSave(newTodo);
Собственно тож самое. Инпут уже почистился, а запрос еще идет

2024-06-19 09:00 UTC, myaak commented on src/App.tsx
> +export type TodoListElem = {
Обычно такие штуки называют TodoItem или просто Todo.

Но чаще описываем интерфейсами и пишем `ITodo`

2024-06-19 09:00 UTC, myaak commented on src/components/TodoInputForm.tsx
> +    <StyledForm id="todoInsert">
А где id используется, не нашел

2024-06-19 09:00 UTC, myaak commented on src/components/TodoInputForm.tsx
> +          onChange={(e) => setTodoInput(e.target.value)}
Чтобы в таких случаях писать меньше приколов можно доставать `e.target.value` в компоненте и написать просто
`onChange={setTodoInput}`

2024-06-19 09:00 UTC, myaak commented on src/components/TodoListElem.tsx
> +  & > div {
Аааааа, плохо на селекторы вешать такие вещи.

2024-06-19 09:00 UTC, myaak commented on src/components/TodoListElem.tsx
> +        checked={todo_item.isDone ? true : false}
Зачем. у тебя isDone и так boolean.
`checked={todo_item.isDone}`

2024-06-19 09:00 UTC, myaak commented on src/components/TodoListElem.tsx
> +    const formJson = Object.fromEntries(formData.entries());
Интересный подход, но можно было и стейтами сделать.

2024-06-19 09:00 UTC, myaak commented on src/components/TodoInputForm.tsx
> +    padding: 10px 15px;
Странные цифры паддинга, даже не четные

2024-06-19 09:03 UTC, IvanKoigerov commented
Ещё кстати, тк ты побежал дальше нужного, ты не знаешь какой стек нужно использовать))
Одну библиотеку ты тут забыл) 
Так что нужно будет переписывать, а вот какую)))
Как ты думаешь?

2024-06-19 09:05 UTC, IvanKoigerov commented on src/App.tsx
> +const StyledList = styled.ul`
ещё лучше в компонентах уносить эти вещи вниз компоненты, а не писать сверху
Также пишем `styled('ul')`, для общей идентичности

2024-06-19 09:08 UTC, IvanKoigerov commented on src/components/TodoListElem.tsx
> +    const form = e.target as HTMLFormElement;
Смысл тут типизировать, типизируй в `(e: Type) =>`, as используем прям в крайнем случае, это не красиво, не всегда читабельно, а также в этой ситуации ты можешь передать любую `e`, хоть стрингу, а это плохо

2024-06-19 09:08 UTC, IvanKoigerov commented on src/components/TodoListElem.tsx
> +    const formJson = Object.fromEntries(formData.entries());
Да и лучше сделай на стейте, хотел бы именно такую реализацию увидеть

2024-06-19 09:19 UTC, IvanKoigerov commented
Выложи свой пр на https://stackblitz.com, чтобы потыкаться можно было

2024-06-21 03:10 UTC, majishanred commented
https://stackblitz.com/~/github.com/majishanred/webbee-todo

2024-06-23 13:24 UTC, majishanred commented on src/App.tsx
> +  function onAdd(todo_item: TodoListElemBody) {
Поменял на стрелки, но не очень понял 1 предложение, так что добавил useСallback и memo для деток.

2024-06-23 13:59 UTC, majishanred commented
> Ещё кстати, тк ты побежал дальше нужного, ты не знаешь какой стек нужно использовать)) Одну библиотеку ты тут забыл) Так что нужно будет переписывать, а вот какую))) Как ты думаешь?

MUI?

2024-06-24 13:27 UTC, majishanred commented
@IvanKoigerov @myaak

2024-06-24 15:51 UTC, myaak commented
Да, должен быть MUI

2024-06-24 15:56 UTC, myaak requested changes
Давай сделаем три компонента.
1. Фильтр
2. ТудуЛист
3. Форма добавления туду

Очевидно ну можно разбить туду лист на todoItem, но должно быть три главных

2024-06-24 15:56 UTC, myaak commented on src/interfaces/ITodoItem.ts
> +export interface ITodoItemBody extends Omit<ITodoItem, 'id'> {}
Такие вещи обычно называются EntityCreate для этого примера `ITodoItemCreate` или просто `TodoItemCreate`

2024-06-24 15:56 UTC, myaak commented on src/App.tsx
> +  );
Вынесем по логике

2024-06-24 15:56 UTC, myaak commented on src/components/TodoInputForm.tsx
> +    setTodoInput(inputRef.current!.value);
! Плохой тон. Сделай проверку. Он не просто так жалуется.
Например 
`if (!inputRef.current) {
     return;
}
set()
`

2024-06-26 10:59 UTC, myaak requested changes

2024-06-26 10:59 UTC, myaak commented on src/components/TodoFilter.tsx
> +  }, 500);
А давай вынесем фильтр в контекст, чтобы при кнопке add не рендерился фильтр.
Фильтр должен рендериться только тогда когда ты пишешь в него.
А так он рендерится когда добавляешь таску тоже.

Давай вынесем фильтр в контекст.

2024-06-26 11:09 UTC, myaak commented on src/components/TodoItem.tsx
> +};
Раз есть отдельный файл с типами, то давай туда.

2024-06-26 11:09 UTC, myaak commented on src/components/TodoItem.tsx
> +      <Checkbox checked={todoItem.isDone} onChange={handleCheckboxClick} />
Можно todoItem деструктурировать в начале, чтобы не писать постоянно

2024-06-26 11:09 UTC, myaak commented on src/components/TodoItem.tsx
> +    <TodoStyledBox component="div">
Box и есть div

2024-06-26 11:09 UTC, myaak commented on src/components/TodoInputForm.tsx
> +    };
Можно написать какую-то константу или тут имплисит задать, чтоб если у тебя в типах поле поменяется ТС ругался

2024-06-26 11:09 UTC, myaak commented on src/App.tsx
> +    }
У тебя вроде не создается несколько тасок. Зачем проверка на массив? К тому же можно провеить Array.isArray(newTodo)

2024-06-26 11:09 UTC, myaak commented on src/App.tsx
> +      if (!newTodo.task) return;
Такие проверки лучше вообще в самый верх выносить, чтобы вообще не идти дальше по функции

2024-06-26 11:09 UTC, myaak commented on src/components/TodoInputForm.tsx
> +    setInput(e.target.value);
Вообще можно и так. А можно прям внутри textField написать. Не криминал

2024-06-26 11:09 UTC, myaak commented on src/components/TodoList.tsx
> +        <TodoListElem key={todo.id} todoItem={todo} onUpdate={onUpdate} onDelete={onDelete}></TodoListElem>
Пройдись везде по компонентам. Тут вот например нет смысла в двойном теге. Пиши `<TodoListElem />`, а еще нейминг должен быть наверное TodoItem), а не просто файл

2024-06-27 14:03 UTC, majishanred commented on src/App.tsx
> +    }
Ты мне замечаниях оставил:
![image](https://github.com/majishanred/webbee-todo/assets/58140063/8114348e-eb4c-4532-9632-edd207cfd202)

2024-06-29 16:13 UTC, myaak commented on src/App.tsx
> +    }
оставил замечание что ты не колбеком из предыдущего значения пушишь, а используешь текущее значение стейта.

2024-07-01 13:57 UTC, myaak requested changes

2024-07-01 13:57 UTC, myaak commented on src/components/TodoFilter.tsx
> +const TodoFilter = memo(function TodoFilter() {
какое мемо

2024-07-01 13:57 UTC, myaak commented on src/components/TodoList.tsx
> +        <TodoItem key={todo.id} todoItem={todo} onUpdate={dispatch} onDelete={dispatch} />
Зачем передаешь пропом? У тебя это в контексте есть

2024-07-01 13:57 UTC, myaak commented on src/components/TodoFilter.tsx
> +import UpdateFilterContext from '../contexts/UpdateFilterContext';
Ошибки при запуске проекта, у тебя тут с большой буквы, а файл с маленькой.

2024-07-01 13:57 UTC, myaak commented on src/contexts/ReadTodoContext.ts
> +export const TodoReadContext = createContext<ITodoItem[]>([]);
Не совсем вижу смысл в такой структуре. Я бы прям в файле объявил оба контекста и там же написал провайдер для них.

2024-07-01 13:57 UTC, myaak commented on src/components/TodoInputForm.tsx
> +    dispatch({ todo: newTodo, type: 'add' });
у тебя этот dispatch по факту setState. Не понятно к чему он относится. Напиши хотя бы `dispatchTodoList`, или вообще setTodoList. Да и type наверное нет смысла юзать.
Зачем мне писать
`dispatch({ todo: newTodo, type: 'add' }); dispatch({ todo: newTodo2, type: 'add' });`, если хочу добавить другую тудушку еще (вдруг).

2024-07-01 13:57 UTC, myaak commented on src/contexts/WriteTodoContext.ts
> +export const WriteTodoContext = createContext<Dispatch<TodoAction>>(() => {});
Обычно ему задают дефолт значение `null` или `{}`

2024-07-01 13:57 UTC, myaak commented on src/prodviders/TodoProvider.tsx
> +  const [tasks, dispatchActions] = useReducer(TodoReducer, defaultTasks);
useReducer не думаю что есть лютый смысл использовать. Думаю тут useState нормально бы справился. Го переделаем

2024-07-02 10:27 UTC, myaak approved these changes

2024-07-02 10:27 UTC, myaak commented on src/components/TodoItem.tsx
> +        <ButtonGroup disableRipple={true} sx={{ marginLeft: 'auto' }}>
true по дефолту.
можно написать просто `disableRipple`

2024-07-02 10:27 UTC, myaak commented on src/components/TodoItem.tsx
> +  };
Наверное по хорошему это в одно место вынести, а то у тебя делит в одном, создание в другом компоненте. (ИМХО)

2024-07-02 10:47 UTC, IvanKoigerov commented on src/components/TodoFilter.tsx
> +    if (!setFilter) return;
Лучше создавать обертку, которая будет ошибки выкидывать, чтобы не делать такие проверки

2024-07-02 10:47 UTC, IvanKoigerov commented on src/components/TodoInputForm.tsx
> +import { v1 as uuidv1 } from 'uuid';
Я бы на твоем месте не юзал бы библу для уникальных id
А просто сам создавал id

2024-07-02 10:47 UTC, IvanKoigerov commented on src/components/TodoInputForm.tsx
> +  const saveTodos = useContext(WriteTodoContext);
save, это сохранение, лучше set или create

2024-07-02 10:47 UTC, IvanKoigerov commented on src/components/TodoInputForm.tsx
> +  const handleOnCreate = () => {
будто бы нет смысла добавлять слово `handle`, обычно редко так делаем, но это нормально

2024-07-02 10:47 UTC, IvanKoigerov commented on src/components/TodoInputForm.tsx
> +      <TextField placeholder="Type task here" value={input} onChange={handleOnChange} sx={{ width: '70%' }} />
Не очень круто использовать % значение ширены и высоты, 100% и 50% можем спокойно использовать. А вот такие вещи уже не очень, не совсем понятно каким он размером по итогу будет

2024-07-02 10:47 UTC, IvanKoigerov commented on src/components/TodoItem.tsx
> +  const { task, isDone } = todoItem;
А почему просто не передавать {task, isDone} в пропы, чтобы вот так не распаковывать

2024-07-02 10:47 UTC, IvanKoigerov commented on src/components/TodoItem.tsx
> +
Ну и тут также, можно сделать обертку, которая будет выкидывать ошибку если нет значения

2024-07-02 10:47 UTC, IvanKoigerov commented on src/components/TodoList.tsx
> +  );
лучше такие вещи расписывать нормально с if, иначе теряется читабельность

2024-07-02 10:47 UTC, IvanKoigerov commented on src/interfaces/ITodoItem.ts
> +}
`I` устарела, обычно так не описывают сейчас
Сейчас используют либо `Props`, если прокидываешь в компонент, а если как тип какого-то значение, то просто название сущности, ну и если нужно можно добавить `Type`

В твоем варианте самое корректное название это просто `ToDo`

2024-07-02 10:47 UTC, IvanKoigerov commented on src/interfaces/ITodoItem.ts
> +}
Сейчас не парься, не меняй, просто на будущее.

2024-07-02 10:49 UTC, IvanKoigerov commented
Пару моментов поправь, напиши мне и потом можешь начинать делать todo c state Manager в новой ветку, от этой

2024-07-02 11:07 UTC, myaak commented on src/components/TodoItem.tsx
> +  const { task, isDone } = todoItem;
Если пропов станет 100 - будет лень. Лучше передать фул, как-будто

2024-07-08 08:00 UTC, IvanKoigerov commented on src/utils.ts
Круто

2024-07-08 10:24 UTC, merged